models/Book.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "books".
 *
 * @property integer $id
 * @property string $name
 * @property string $date_create
 * @property string $date_update
 * @property string $preview
 * @property string $date
 * @property string $author
 * @property integer $author_id
 */
class Book extends \yii\db\ActiveRecord
{

    public $author;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'books';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['date_create', 'date_update', 'date'], 'safe'],
            [['author_id'], 'validateAuthorId'],
            [['name'], 'string', 'max' => 100],
            [['preview'], 'string', 'max' => 300],
            ['author', 'string'],
            ['date', 'date', 'format' => 'yyyy-M-d H:m:s'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'date_create' => 'Date Create',
            'date_update' => 'Date Update',
            'preview' => 'Preview',
            'date' => 'Date',
            'author_id' => 'Author ID',
            'author' => 'Author',
        ];
    }

    /**
     * @inheritdoc
     * @return BookQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new BookQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($insert) {
                $this->date_create = date("Y-m-d H:i:s");
            } else {
                $this->date_update = date("Y-m-d H:i:s");
            }
            return true;
        }
        return false;
    }

    /**
     * Get author property
     * @return type
     */
    public function getAuthor()
    {
        if (empty($this->author)) {
            $authorRow = Author::findOne(['id' => $this->author_id]);
            $this->author = $authorRow->firstname . ' ' . $authorRow->lastname;
        }
        return $this->author;
    }

    /**
     * Validation author id
     * @param type $authorId
     */
    public function validateAuthorId($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $authorId = $this->{$attribute};

            $author = Author::findOne(['id' => $authorId]);
            if (empty($author)) {
                $this->addError($attribute, 'Incorrect author');
            }
        }
    }

}

controllers/BooksController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Book;
use app\models\BookSearch;
use app\models\Author;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

/**
 * BooksController implements the CRUD actions for Book model.
 */
class BooksController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $authors = Author::getAllAuthors();

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'authors' => $authors,
        ]);
    }

    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $authors = Author::getAllAuthors();
        $model = $this->findModel($id);

        if (Yii::$app->getRequest()->isAjax) {
            return $this->renderPartial('view', [
                        'model' => $model,
                        'authors' => $authors,
            ]);
        } else {
            $this->layout = 'empty';
            return $this->render('view', [
                        'model' => $model,
                        'authors' => $authors,
            ]);
        }
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Book();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            $authors = Author::getAllAuthors();

            $this->layout = 'empty';
            return $this->render('create', [
                        'model' => $model,
                        'authors' => $authors,
            ]);
        }
    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $authors = Author::getAllAuthors();

            $this->layout = 'empty';
            return $this->render('update', [
                        'model' => $model,
                        'authors' => $authors,
            ]);
        }
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/books/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Book */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'preview')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date')->textInput(['placeholder' => 'YYYY-MM-DD HH:MM:SS']) ?>

    <?= $form->field($model, 'author_id')->dropDownList($authors) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/books/_search.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\BookSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<?php
Pjax::begin([
    'id' => 'booksSearchPjaxForm',
    'options' => ['class' => 'book-search']
])
?>
<?php
$form = ActiveForm::begin([
            'id' => 'booksSearchForm',
            'action' => ['index'],
            'method' => 'get',
            'options' => [
                'data-pjax' => true,
            ]
        ]);
?>

<?= $form->field($model, 'name') ?>

<?= $form->field($model, 'author_id')->dropDownList(["" => ""] + $authors) ?>

<?= $form->field($model, 'date_from')->input('text', ['placeholder' => 'YYYY-MM-DD HH:MM:SS']) ?>

<?= $form->field($model, 'date_to')->input('text', ['placeholder' => 'YYYY-MM-DD HH:MM:SS']) ?>

<div class="form-group">
    <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
    <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
</div>

<?php ActiveForm::end(); ?>

<?php Pjax::end(); ?>

views/books/_viewmodal.php
<?php

use yii\bootstrap\Modal;
use yii\helpers\Html;

Modal::begin([
    'id' => 'viewForm',
    'header' => 'View form',
]);
?>

<div class="view-form-content">

</div>

<div class="form-group">
    <?= Html::button('Cancel', ['class' => 'btn btn-default', 'data-dismiss' => 'modal']); ?>
</div>

<?php
Modal::end();

views/books/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Book */

$this->title = 'Create Book';
?>
<div class="book-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
        'authors' => $authors,
    ])
    ?>

</div>

views/books/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BookSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Books';
?>

<?php echo $this->render('_viewmodal'); ?>

<div class="book-index">
    <p>
        <?= Html::a('Create Book', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <h1><?= Html::encode($this->title) ?></h1>  

    <?php echo $this->render('_search', ['model' => $searchModel, 'authors' => $authors]); ?>

    <?php Pjax::begin(['id' => 'booksGrid']); ?>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            'name',
            'preview',
            'author',
            'date',
            'date_create',
            ['class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'view' => function($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                                    'class' => 'full-view',
                                    'title' => 'View',
                                    'data-bookid' => $model->id,
                                    'data-url' => Url::to(['books/view', 'id' => $model->id]),
                                    'data-pjax' => 0,
                        ]);
                    },
                            'update' => function($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                                    'class' => 'edit-view',
                                    'title' => 'Edit',
                                    'data-bookid' => $model->id,
                                    'data-url' => Url::to(['books/update', 'id' => $model->id]),
                                    'data-pjax' => 0,
                        ]);
                    }
                        ],
                    ],
                ],
            ]);
            ?>
            <?php Pjax::end(); ?>

</div>

views/books/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Book */

$this->title = 'Update Book: ' . $model->name;
?>
<div class="book-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
        'authors' => $authors,
    ])
    ?>

</div>

views/books/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Book */

$this->title = 'View Book: ' . $model->name;
?>
<div class="book-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'date_create',
            'date_update',
            'preview',
            'date',
            [
                'label' => 'Author',
                'value' => $authors[$model->author_id],
            ],
        ],
    ])
    ?>

</div>

<?php
$this->registerJs('
    if (window.opener) {
        window.opener.$(window.opener.document).trigger("book-edit");
    }
');